In [ ]:
Soru 1-Bir listeyi tek boyutlu bir diziye dönüştüren ve şekil ve boyut bilgisini ekrana basan kodu yazınız.

In [ ]:
Soru_2-   x = np.array([[[1,2,3],[1,2,3],[1,9,7]],[[1,2,3],[4,5,6],[4,5,6]],[[1,2,3],[4,5,6],[4,5,6]]]) yandaki listeyi üç boyutlu diziye çeviren ve  tüm boyutlardaki unique değerlerini döndüren bir program yazınız.

In [ ]:
Soru-3 Parametre olarak bir array alan ve bu arraye ilişkin boyut şekil ve veri tipi bilgisini aynı anda ekrana basan bir fonsiyon yazınız.

In [ ]:
Soru_4:   8*8 iki boyutlu ve ağaşıdaki paterni döndüren kodu yazınız.

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
Soru_5-   x = np.array([[0, 10, 20], [20, 30, 40]]) yandaki dizide 10 dan büyük değerlerin indexini döndüren kodu yazınız

In [ ]:
soru-6-   3*5 iki boyutlu ve tüm değerlerinin 99 olduğu bir dizi döndüren kodu yazınız.

In [ ]:
soru-7  lineer artış gösteren değerleri  2*2*6 şeklinde ve üç boyutlu dizi olarak döndüren kodu yazınız.

In [ ]:
soru-8  x = np.array([[2, 4, 6], [6, 8, 10]], np.int32) yandaki arr deki 3 ve 5 inci index değerinindeki rakamları döndüren kodu yazınız.

In [1]:
import numpy as np

In [2]:
#Cevap 1:
list1 = [1, 2, 3, 4, 5, 6]
arr = np.array(list1)
print(arr.shape)
print(arr)


(6,)
[1 2 3 4 5 6]


In [3]:
#Soru 2: listeyi üç boyutlu diziye çeviren ve  tüm boyutlardaki unique değerlerini döndüren bir program yazınız.
x = np.array([[[1,2,3],[1,2,3],[1,9,7]],[[1,2,3],[4,5,6],[4,5,6]],[[1,2,3],[4,5,6],[4,5,6]]])
x


array([[[1, 2, 3],
        [1, 2, 3],
        [1, 9, 7]],

       [[1, 2, 3],
        [4, 5, 6],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6],
        [4, 5, 6]]])

In [4]:
x.shape

(3, 3, 3)

In [5]:
np.unique(x)


array([1, 2, 3, 4, 5, 6, 7, 9])

In [124]:
#Soru-3 Parametre olarak bir array alan ve bu arraye ilişkin boyut şekil ve veri tipi bilgisini aynı anda ekrana basan bir fonsiyon yazınız.

a = np.arange(24).reshape(3,2,2,2)

def dimensionType(a):
    print(a.ndim)
    print(type(a))

dimensionType(a)


"""print("my array is:\n", a,
      "ndim of array:", a.ndim,
      "shape of array:", a.shape,
      "data type of array:", type(a))"""



4
<class 'numpy.ndarray'>


'print("my array is:\n", a,\n      "ndim of array:", a.ndim,\n      "shape of array:", a.shape,\n      "data type of array:", type(a))'

In [128]:
# Soru_4:   8*8 iki boyutlu ve ağaşıdaki paterni döndüren kodu yazınız.

#a = np.eye(8)
#print(a)

b = np.array([1,0,1,0,1,0,1,0], dtype=int)

c = np.array([0,1,0,1,0,1,0,1], dtype=int)

a = np.concatenate((c,b)*4).reshape(8,8)

print(a)


# print

#d = 
#print(d)
        


"""array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])"""




[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


'array([[0, 1, 0, 1, 0, 1, 0, 1],\n       [1, 0, 1, 0, 1, 0, 1, 0],\n       [0, 1, 0, 1, 0, 1, 0, 1],\n       [1, 0, 1, 0, 1, 0, 1, 0],\n       [0, 1, 0, 1, 0, 1, 0, 1],\n       [1, 0, 1, 0, 1, 0, 1, 0],\n       [0, 1, 0, 1, 0, 1, 0, 1],\n       [1, 0, 1, 0, 1, 0, 1, 0]])'

In [129]:
# Soru_5-   yandaki dizide 10 dan büyük değerlerin indexini döndüren kodu yazınız
x = np.array([[0, 10, 20], [20, 30, 40]]) 
print(x)
#print(x)
#print(x[x>10])
#print(np.where(x[x>10]))
#print(np.where([x>10]))

result = np.where(x>10)
print(result)






[[ 0 10 20]
 [20 30 40]]
(array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


In [97]:
# soru-6-   3*5 iki boyutlu ve tüm değerlerinin 99 olduğu bir dizi döndüren kodu yazınız.

print(np.full((3,5), 99))


[[99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]]


In [118]:
# soru-7  lineer artış gösteren değerleri  2*2*6 şeklinde ve üç boyutlu dizi olarak döndüren kodu yazınız.

print(np.linspace(1,25, 24).reshape(2,2,6))



[[[ 1.          2.04347826  3.08695652  4.13043478  5.17391304
    6.2173913 ]
  [ 7.26086957  8.30434783  9.34782609 10.39130435 11.43478261
   12.47826087]]

 [[13.52173913 14.56521739 15.60869565 16.65217391 17.69565217
   18.73913043]
  [19.7826087  20.82608696 21.86956522 22.91304348 23.95652174
   25.        ]]]


In [122]:
#soru-8  yandaki arr deki 3 ve 5 inci index değerinindeki rakamları döndüren kodu yazınız.
x = np.array([[2, 4, 6], [6, 8, 10]], np.int32) 
print(x[(1, 1),(0, 2)])







[ 6 10]
