# Numpy Practice

### 1. Import the numpy package under the name as np 

In [14]:
import numpy as np


### 2. Print the numpy version and the configuration

In [15]:
print(np.__version__)
np.show_config()


1.20.3
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/hatic/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/hatic/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/hatic/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/hatic/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/hatic/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/hatic/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/hatic/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/hatic/anaconda3\\Library\\include']


### 3. Create a null vector of size 10

In [105]:
arr1 = np.zeros(10)
arr1



array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 4. How to get the documentation of the numpy add function from the command line?

In [107]:
# np.info(np.add)

# hocanin yontemi asagida
!python -c "import numpy;numpy.info(numpy.add)"


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

### 5. Create a null vector of size 10 but the fifth value which is 1

In [20]:
arr2 = np.zeros(10)
arr2[4] = 1
arr2


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### 6. Create a vector with values ranging from 10 to 49

In [27]:
vec1 = np.arange(10, 50)
vec1


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 7. Reverse a vector (first element becomes last)

In [28]:
vec1[::-1]


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### 8. Create a 3x3 matrix with values ranging from 0 to 8

In [29]:
mat1 = np.arange(0, 9).reshape(3, 3)
mat1


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 9 Find indices of non­zero elements from [1,2,0,0,4,0]

In [30]:
nonz = np.nonzero([1,2,0,0,4,0])
nonz

# nonzero methodu 0 olmayan degerlerin indexlerini donduruyor
# np.where ile de yapilabilir 
# arr = np.array([1,2,0,0,4,0])
# np.where(arr != 0)

(array([0, 1, 4], dtype=int64),)

### 10. Create a 3x3 identity matrix

In [134]:
mat2 = np.eye(3,3)
mat2

# sadece np.eye(3) de yeterli olurdu birim matris her turlu esit satir esit sutunda olusmak zorunda old icin
# boyut artirmak istersem reshape yeterli

array([[1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.]])

### 11. Create a 3x3x3 array with random values

In [150]:
ranm = np.random.uniform(10, 100, 50)  # bunu normalde randomla yapmistim
#rann = np.random.normal(10, 100, 50)
ranm
# ranc = np.random.choice(["buyuk", "orta", "kucuk"], 50)

#ranc = np.random.random_sample()  # sample in diger random komutlari ile farkina bakabilirsin orneklem ile alakali
# ranc = np.random.shuffle(["buyuk", "orta", "kucuk"])  # buraya array ya da cok boyutlu bi deger girmek lazim
# print(ranc)
# random un icine sadece size girebiliyoruz 0-1 araliginda kac tane sayi cekmek istedigimizi giriyoruz
# alt deger ust deger ve size giriyorusun randint icin
# randn normal dagilim verityor, boyut degeri giriyorsun kisaca
# rand uniform (can egrisi) dagilimi, boyut giriyorsun
# uniform methodu ile istedigimiz iki sayi arasinda size vererek dondurebiliyoruz
# .normal() methodu normal dagilim yapiyor calisma stili uniform gibi
# uniform normal dagilimli istatistiki gausstian* dagilimi can egrisi gibi 
# choice verdigin liste ya da degerden istedigin sayida deger donduruyor


""" Emincan'in cozumu
ranm = np.random.randint(10,100,27).reshape(3,3,3)
print(ranm)
"""

array([16.97394875, 80.89665302, 64.34059149, 51.82901296, 24.02803101,
       11.73925588, 33.90564955, 11.54166043, 58.89405308, 96.83157617,
       34.62921532, 97.24317588, 42.02198879, 84.84599933, 32.79965154,
       44.55181863, 50.99467872, 92.10109972, 62.49779118, 83.02552009,
       39.42370895, 54.92830772, 64.7033751 , 34.70325273, 34.74454469,
       63.27869019, 13.96467115, 52.17380914, 19.70641281, 15.82182426,
       23.95780668, 90.96980457, 65.71761741, 27.71240953, 94.68648251,
       24.01112926, 72.27933262, 89.1998462 , 59.19936422, 79.71457223,
       36.91367322, 56.01483477, 33.19783947, 51.85296834, 61.52611117,
       24.71103457, 13.84527224, 81.94688942, 22.76606139, 75.77318955])

### 12. Create a 10x10 array with random values and find the minimum and maximum values

In [133]:
ranm2 = np.random.random((10, 10))
print(ranm2)
print("max:", ranm2.max())
print("min:", ranm2.min())

"""
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)
"""

""" Emincan'in cozumu:
Z = np.random.randint(100,1000,100).reshape(10,10)
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)
"""

[[0.36728195 0.8453881  0.24535936 0.51710523 0.80643963 0.61006352
  0.03752919 0.6064157  0.5534769  0.88159646]
 [0.06193935 0.8394152  0.04893505 0.23273443 0.38317761 0.22790532
  0.16055271 0.66701175 0.70780596 0.82738769]
 [0.37766598 0.18497249 0.49231489 0.23683052 0.04274932 0.35098726
  0.42111341 0.78355906 0.46479405 0.44907184]
 [0.01493321 0.98742818 0.03551944 0.87343751 0.48868103 0.91453989
  0.64472118 0.75689672 0.05841501 0.87285703]
 [0.34104041 0.76748018 0.6839017  0.20730974 0.96456411 0.67305284
  0.36947705 0.50793333 0.07004689 0.78100284]
 [0.86868706 0.67615962 0.93197232 0.21761859 0.98478875 0.18917107
  0.7307406  0.7513447  0.32743772 0.29649412]
 [0.44571526 0.39565831 0.87332265 0.20833338 0.88075229 0.67794252
  0.9466313  0.08111029 0.08010084 0.82512779]
 [0.61913801 0.30229721 0.39806085 0.74167511 0.58731601 0.74197202
  0.28739563 0.144859   0.76767508 0.19972691]
 [0.76790165 0.26186364 0.28163712 0.44248161 0.20249737 0.66127769
  0.05950775

### 13. Create a random vector of size 30 and find the mean value

In [40]:
ran3 = np.random.random(30)
avg = ran3.mean()
print(ran3)
print(avg)

""" Emincan'in cozumu:
Z = np.random.randint(50,1000,30)
avrg = Z.mean()
avrg
"""

[0.54840534 0.17516818 0.81363769 0.06498548 0.02835386 0.40942571
 0.51855548 0.01773619 0.19075396 0.54088799 0.80836653 0.80705622
 0.94822156 0.44429214 0.01821279 0.40924348 0.85591276 0.30421607
 0.769181   0.71775594 0.10445585 0.53449573 0.98675861 0.21191498
 0.56346948 0.90651785 0.52466122 0.43976002 0.54738302 0.31102729]
0.4840270808111445


### 14. Create a 2d array with 1 on the border and 0 inside

In [155]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Yukaridaki cozum aslinda su sorunun cevabi: How to add a border (filled with 0's) around an existing array?


"""Z = np.ones((5, 5))
Z[1:-1,1:-1] = 0
print(Z)"""

np.inf  # string i ya da rakami float a ceviriyor

# Hoca indexli olan cozumu uyguladi


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


'Z = np.ones((5, 5))\nZ[1:-1,1:-1] = 0\nprint(Z)'

### 15. What is the result of the following expression?

In [66]:
# Orijinal dokumandaki "How to add a border (filled with 0's) around an existing array?" sorusunun cevabi asagida

"""Z = np.ones((5,5))

Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)

print(Z)"""

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)  # degerlerin tipi ile alakali bir problem olabilir

# internetteki cevap yukarida, hocanin cevabini merakla bekliyoruz..

# CEVAPLAMADI


nan
False
False
nan
True
False


### 16. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [68]:
Dia = np.diag(1 + np.arange(4), k =- 1)  # duserek gitsin diye k-1 dedik
print(Dia)

# -1 ilk satiri 0 yapiyor, +1'de ilk sutun 0 oluyor, axis ayari bu
# dagilimi kendi ayarlamanizla alakali bir komuttur diagonal
# parantez icine liste olarak bu rakamlari eklersen de oluyor oyle de yapanlar olmus
# range 4'te 4 dahil olmadigi icin +1 ile basladik

""" Emincan'in kodu hoca yazdi:
Z = np.diag([1, 2, 3, 4]m k = -1)
yukarida bahsettigim listeli olan cozum bu
"""


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [157]:
#dia = np.diag([5,1,7,9])
dia2 = np.diag([1,2,3,4], k = -1)
dia2
#dia


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

### 17. Create a 8x8 matrix and fill it with a checkerboard pattern

In [164]:
# checkerboard pattern'den kasit hep 1, 0, 1, 0... seklinde devam etmesi gerekiyor (gorsel olarak satranc tahtasi gibi)

# https://www.geeksforgeeks.org/python-program-print-checkerboard-pattern-nxn-using-numpy/

# https://stackoverflow.com/questions/2169478/how-to-make-a-checkerboard-in-numpy

def checkerboard(shape):
    return np.indices(shape).sum(axis=0) % 2

shape = (8, 8)

checkerboard(shape)

# yukaridaki cozum stackoverflow'dan alinma, en kisa cozum, aciklamasi altinda.

# kaggle'daki cozum biraz amele isi, bu fonksiyon tum checkerboardlarda calisiyor

# kaggle linki: https://www.kaggle.com/code/utsav15/100-numpy-exercises/notebook

# Kaggle'daki cozum
"""Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)"""


# Hoca Kaggle'daki cozumu yapti

[[0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]]


In [162]:
def checkerboard(shape):
    return np.indices(shape).sum(axis=0) % 2

shape = (8, 8)

checkerboard(shape)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int32)

### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [73]:
print(np.unravel_index(100,(6,7,8)))

# ravel = karmasik demek

# hocanin aciklamasini ekle

(1, 5, 4)


### 19. Create a checkerboard 8x8 matrix using the tile function

In [165]:
# tile fonksiyonu arraylerin tekrarindan matrix olusturuyor, geeksforgeekste makale save ettim bununla ilgili

tf = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(tf)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 20. Normalize a 5x5 random matrix

In [82]:
mtx = np.random.rand(5,5)
print(mtx)
norm = np.linalg.norm(mtx)
nrmlzd = mtx / norm
print("normalized array:\n", nrmlzd)

# source: https://www.adamsmith.haus/python/answers/how-to-normalize-an-array-in-numpy-in-python

""" Kaggle cozumu:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)
"""

# sayinin en kucuk degeri 0, en buyuk degerinin 1 olmasi demek normalize etmek

[[0.25075808 0.71158851 0.90921355 0.59082434 0.93682176]
 [0.41277502 0.63095881 0.02716778 0.84428876 0.79814282]
 [0.52515088 0.98430218 0.38526142 0.44851382 0.71891999]
 [0.78151395 0.17958275 0.97927456 0.19703414 0.16442426]
 [0.79387541 0.8535862  0.19402527 0.77513664 0.80358546]]
normalized array:
 [[0.07573146 0.21490687 0.27459162 0.17843488 0.28292957]
 [0.1246622  0.19055589 0.00820494 0.25498368 0.24104714]
 [0.15860084 0.29726914 0.11635281 0.13545567 0.21712105]
 [0.23602506 0.05423579 0.29575075 0.05950629 0.04965778]
 [0.23975834 0.2577916  0.05859758 0.23409904 0.24269087]]


### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [90]:
mat53 = np.arange(15).reshape(5, 3)
mat32 = np.arange(6).reshape(3, 2)

result = mat53 @ mat32
print(result)

# Alternatif yazim:
res = np.dot(mat53, mat32)
print("Alternatif cozum:\n", res)


[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]
Alternatif cozum:
 [[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


### 22. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [166]:
neg = np.arange(11)
neg[(3 < neg) & (neg <= 8)] *= -1
print(neg)
type(neg)


[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


numpy.ndarray

In [168]:
arr = np.arange(11)
arr[3:9] *= -1
arr
type(arr)

numpy.ndarray

### 23. Extract the integer part of a random array using 5 different methods

In [92]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))  # zemin - tam sayi bolumunu aliyor
print (np.ceil(Z)-1)  # float bir degeri yukari yuvarliyor
print (Z.astype(int))  # tip degisimi yapiyor
print (np.trunc(Z))  # muhtemelen asagi yuvarliyor

# cozmedi


[9. 9. 9. 7. 1. 2. 8. 1. 5. 8.]
[9. 9. 9. 7. 1. 2. 8. 1. 5. 8.]
[9. 9. 9. 7. 1. 2. 8. 1. 5. 8.]
[9 9 9 7 1 2 8 1 5 8]
[9. 9. 9. 7. 1. 2. 8. 1. 5. 8.]


### 24. How to round away from zero a float array ?

In [112]:
""" Kaggle Cozumu:
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))
print(Z)"""

"""def round_array(x,y):  # fonksiyonu olusturmasinin sebebi array e round u rahatca uygulayabilmek icin
    return np.round(x,y)

test = np.array([32.11, 51.5, 0.112])
print(round_array(test,0))"""

# Source the code of above: https://www.projectpro.io/recipes/round-away-from-zero-float-array

Z = np.random.uniform(-10,+10,10)
print(np.trunc(Z + np.copysign(0.5, Z)))
np.round



#trunc komutu 0.5 in altiysa virgulden sonrasini 1 azalt, fazlaysa arttir gibi bu komut bu sekilde calisiyor


[ 6. -7. -2. -5.  2. -4. -9.  5. -1.  8.]


In [ ]:
test = np.array([32.11, 51.5, 0.112])


### 25. Create a 5x5 matrix with row values ranging from 0 to 4

In [97]:
rowArr = np.zeros((5,5))
rowArr += np.arange(5)
print(rowArr)

# np.full((5,5),[0,1,2,3,4]) alternatif cozum

#5. range e kadar birer birer ekle

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### 26. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [98]:
vec = np.linspace(0, 1, 11, endpoint = False)[1:]
print(vec)


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


### 27. Create a random vector of size 10 and sort it

In [102]:
srtd = np.random.random(10)
srtd.sort()
srtd


array([0.00711841, 0.25930953, 0.27821025, 0.35316916, 0.39449477,
       0.51515332, 0.62539023, 0.69228155, 0.85099637, 0.95763312])

### 28. Consider two random array A anb B, check if they are equal

In [169]:
A = np.random.randint(1, 2, 3)
B = np.random.randint(1, 2, 3)

eq = np.allclose(A, B, atol = 5, rtol = 5)  # atol absolute tolerans, rtol
print(eq)

# allclose birbirlerine esit olup olmadiklarini kontrol eden bir method

True


### 29. Make an array immutable (read­only)

In [114]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

# flags.writeable yazilabilir komutunu False a esitleyerek dosyayi readonly yapiyoruz


ValueError: assignment destination is read-only

### 30. Create random vector of size 10 and replace the maximum value by 0

In [2]:
import numpy as np
Z = np.random.randint(0, 10, 10)
Z[Z.argmax()] = 0
print(Z)

# argmax = enyuksek sayinin indexini verir


[2 7 3 2 0 5 0 5 9 4]


### 31. Create a structured array with xand ycoordinates covering the [0,1]x[0,1] area

In [ ]:
# bunu by gecti

### 32. How to find the closest value (to a given scalar) in an array?

In [116]:
Z = np.arange(100)
print(Z)  # 0 dan 100 e kadar deger olusturdum
v = np.random.uniform(0, 100)
print(v)  # uniform dagilim yaptim can egrisi gibi - bir tane deger sectik
index = (np.abs(Z - v)).argmin()  # abs - absolute - mutlak deger verdik - cikmasin diye
print(Z[index])  # z ile v nin arasindaki farkin en az old indexi bulduk


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
81.30239005580057
81


### 33. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [117]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

# astype kalici olarak degeri degistirmiyor, burada copy = False parametresi ekledigimiz icin orijinali degisiyor


[0 1 2 3 4 5 6 7 8 9]


### 34. What is the equivalent of enumerate for numpy arrays?

In [ ]:
# gostermedi

### 35. Subtract the mean of each row of a matrix

In [118]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
# Y = X - X.mean(axis=1).reshape(-1, 1) 
# yukaridaki (-1, 1) yaziminda mesela shape (1000, 1) ise column cikmazsa reshape(-1,1) koyuyoruz hata olmamasi icin

print(Y)

# keepdims boyutunu sabit tut degistirme demek oluyor True diyince, ML de de kullanacagiz!!!


[[ 0.18957775  0.10448773 -0.05738223  0.08182219 -0.06876557  0.08774686
  -0.20501832  0.06516528 -0.02897402 -0.16865967]
 [ 0.21586679 -0.16255791 -0.38021426 -0.30790784  0.03158355  0.26183768
  -0.21019969  0.12213664  0.25592477  0.17353028]
 [ 0.05737256 -0.05983665 -0.48115808 -0.23925397 -0.0996341   0.26897771
   0.18225085 -0.24219336  0.35055972  0.26291533]
 [ 0.06975638  0.22759074 -0.42324988  0.09535764 -0.1305602  -0.30149043
   0.38629256  0.0295097  -0.42726783  0.47406131]
 [ 0.55992315  0.32124113 -0.28762934  0.22960047 -0.13271081 -0.27639523
   0.13938248 -0.18997412 -0.39992123  0.0364835 ]]


### 36. How to I sort an array by the nth column?

In [3]:
z = np.random.randint(0, 10, (3, 3))
print(z)
print("sorted array: \n", z[z[:,1].argsort()])
# satirlarin tamamini al, sutunlarin 1. indexini al ve onlarin hepsinin sortunu al
# yani 1. sutuna gore indexleri duzenliyor

[[7 3 2]
 [1 1 3]
 [8 6 6]]
sorted array: 
 [[1 1 3]
 [7 3 2]
 [8 6 6]]


### 37. Find the nearest value from a given value in an array

In [122]:
Z = np.random.uniform(0, 1, 10)
print(Z)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)


[0.16469706 0.6635981  0.53890868 0.497444   0.0607984  0.18767184
 0.93516649 0.30653529 0.18269895 0.475183  ]
0.49744399681497264


### 38. Considering a four dimensions array, how to get sum over the last two axis at once?

In [14]:
"""A = np.random.randint(0, 10, (3, 4, 3, 4))
# print(A)
summ = A.reshape(A.shape[: -2] + (-1,)).sum(axis = -1)
print(summ)"""

A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)

# if axis=-1 it will be the last dimension
# axis = 0 ilk boyut 


[[48 66 56 52]
 [41 72 58 29]
 [47 59 56 58]]


### 39. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

In [9]:
A = np.ones((5, 5, 3))
B = 2 * np.ones((5, 5))
print(A * B[:,:, None])

#Broadcasting hatasi alirsak B'nin icindeki gibi indexleme yaparak deneyelim 


[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


### 40. How to swap two rows of an array?

In [12]:
A = np.arange(25).reshape(5, 5)
print(A)
A[[0, 1]] = A[[1, 0]]
print(A)
# A'nin 0. indexi 1. indexine esit olsun, 1. indexi de 0. indexine esit olsun diyoruz bu komutta


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### 41. How to find the most frequent value in an array?

In [131]:
z = np.random.randint(0, 10, 50)
print(z)
print(np.bincount(z).argmax())  # en cok tekrar eden sayinin indexi
# np.bincount
# kaggle cozumu


[8 2 5 8 6 9 1 5 1 1 3 3 7 4 2 7 3 2 9 9 9 6 7 4 9 3 5 1 4 3 7 4 5 3 3 6 0
 0 3 3 9 2 5 0 1 7 2 4 8 5]
3


In [13]:
z = np.random.randint(0, 10, 50)
print(z)
print(z[np.bincount(z).argmax()])
# bincount kendi icerisinde listeyi sort ettikten sonra negatif olmayan her bir degerden kac tane dondurdugunu gosteriyor
# en cok tekrar eden degeri bulmak icin biz boyle yaptik ders sonrasi calismada


[7 9 3 2 4 9 9 2 3 2 2 9 5 6 8 5 0 2 2 1 2 8 9 0 8 8 9 8 1 4 3 4 7 4 5 6 8
 5 0 8 9 9 4 6 9 5 0 0 3 6]
2
