Soru 1: (10, 15, 30, 45, 60) degerlerine sahip numpy dizisi olusturunuz

In [3]:
import numpy as np
myArr = np.asarray([10, 15, 30, 45, 60])
myArr


array([10, 15, 30, 45, 60])

Soru 2: 5-15 arasindaki sayilarla numpy dizisi olusturunuz

In [4]:
my_Arr = np.arange(5, 15)
my_Arr


array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Soru 3: 50-100 arasinda 5'er 5'er artan sayilarla numpy dizisi olusturunuz

In [5]:
my_Arr = np.arange(50, 100, 5)
my_Arr


array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

Soru 4: 10 elemanli 0lardan olusan bir dizi olusturunuz

In [6]:
Arr = np.zeros(10)
Arr


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Soru 5: 10 elemanli 1lerden olusan bir sayi dizisi olusturun

In [7]:
arr = np.ones(10)
arr


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Soru 6: 0-100 arasinda esit aralikli 5 sayi uretin

In [10]:
lin_arr = np.linspace(0, 100, 5)
lin_arr


array([  0.,  25.,  50.,  75., 100.])

Soru 7: 10-30 arasinda rastgele 30 tane tam sayi uretin

In [18]:
import random

ran_arr = np.random.randint(10, 30, 30)
ran_arr


array([13, 15, 15, 17, 28, 15, 21, 29, 16, 14, 13, 13, 22, 11, 18, 18, 29,
       16, 14, 13, 26, 26, 29, 12, 26, 25, 21, 27, 14, 11])

Soru 8: -1 ile 1 arasinda 10 adet sayi uretin 

In [41]:
neg_arr = np.linspace(-1, 1, 10)
print("my answer:", neg_arr)

# cevaplarda su sekilde cozmus: (soruda belirtmemis ama aslinda random ile yapilmasini istemis)
# random.rand methodunun 0 - 1 arasinda rastgele degerler atadigini soylemis
# -1 ile 1 arasinda bir deger uretmek icin random.randn diye bir method varmis
# dolayisiyla cozum: 

randn_arr = np.random.randn(10)
print("result:", randn_arr)


my answer: [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]
result: [-1.32111826 -2.9026715  -0.12738723  0.06345178  0.01254331 -1.27928192
 -1.62818092 -0.18030424  0.33725436  0.1587875 ]


Soru 9: (3x5) boyutlarinda 10-50 arasinda rastgele bir matris olustur

In [99]:
ran_mat = np.random.randint(10, 50, (3, 5))

print("my answer:\n", ran_mat)

#cevaplarda asagidaki gibi cozmus:

rand_ans = np.random.randint(10, 50, 15).reshape(3, 5)
# 3, 5 olarak reshape edebilmek icin 15'i girdi

print("result:\n", rand_ans)


my answer:
 [[30 34 41 16 34]
 [21 24 45 38 14]
 [28 37 25 34 30]]
result:
 [[13 29 24 17 21]
 [31 13 16 38 31]
 [36 25 20 37 47]]


Soru 10: Uretilen matrisin satir ve sutun sayilari toplamlarini hesaplayiniz

In [100]:
rowTotal = rand_ans.sum(axis = 1)
colTotal = rand_ans.sum(axis = 0)

print(rowTotal)
print(colTotal)


[104 129 165]
[80 67 60 92 99]


Soru 11: Uretilen matrisin en buyuk, en kucuk ve ortalama degerleri nelerdir?

In [54]:
print(rand_ans.max())

print(rand_ans.min())

print(rand_ans.mean())


49
12
28.466666666666665


Soru 12: Uretilen matrisin en buyuk degerinin indexi kactir?

In [102]:
print(rand_ans.argmax())  # matrisin en buyuk degerinin indexini verir

print(rand_ans.argmin())  # matrisin en kucuk degerinin indexini verir


14
0


Soru 13: 10-20 arasindaki sayilari iceren dizinin ilk 3 elemanini seciniz

In [57]:
tentw = np.arange(10, 20)

print(tentw[:3])



[10 11 12]


Soru 14: Uretilen dizinin elemanlarini tersten yazdirin

In [103]:
tentw[::-1]




array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

Soru 15: Uretilen matrisin ilk satirini seciniz

In [112]:
#print(tentw)

#print(tentw[0])

print(rand_ans)

print(rand_ans[0])


[[13 29 24 17 21]
 [31 13 16 38 31]
 [36 25 20 37 47]]
[13 29 24 17 21]


Soru 16: Uretilen matrisin 2. Satir 3. Sutunundaki elemani hangisidir? 

In [121]:
print(rand_ans[1][2])  # benim yazdigim

print(rand_ans[1, 2])  # cevapta olan

16
16


Soru 17: Uretilen matrisin tum satirlardaki ilk elemanini seciniz

In [136]:
# print(rand_ans)

print(rand_ans[(0, 1, 2), (0, 0, 0)])

# cevap:

print(rand_ans[:, 0])


[13 31 36]
[13 31 36]


Soru 18: Uretilen matrisin her bir elemaninin karesini aliniz

In [123]:
rand_ans**2


array([[ 169,  841,  576,  289,  441],
       [ 961,  169,  256, 1444,  961],
       [1296,  625,  400, 1369, 2209]], dtype=int32)

Soru 19: Uretilen matris elemanlarinin hangisi pozitif cift sayidir, araligi (-50, +50) arasi yapiniz

In [142]:
"""matrix = np.arange(-50, 50)
matrix
matList = []
for i in matrix:
    if i % 2 == 0 and i > 0:
        matList.append(i)
        
matList"""

rand_ans = np.random.randint(-50, 50, 15).reshape(3, 5)

result = rand_ans % 2 == 0  # boyle yapinca boolean dondurmus oldu

# print(result)

mod0 = rand_ans[rand_ans % 2 == 0]  # cift sayilari dondurdu bu sekilde
# sadece True gelen degerlerin karsiliklarini dondurdu yani
# print(res)
print(rand_ans)

res = mod0[mod0>0]

print(res)


[[-48  -1  10  36  26]
 [ 32  41  30  -7  45]
 [  7 -38  25   1 -17]]
[10 36 26 32 30]
